### ISSUE TITLE
Runtime Error in torch_train.ipynb

### ISSUE THREAD

**Issue by dawson-miller** [JamesSullivan/temporalCN#1]
The file torch_train.ipynb does not run out of the box. The following error is produced:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (80x1 and 127x1)

A full traceback is attached.
![torch_train_error](https://github.com/JamesSullivan/temporalCN/assets/82901642/97adf907-eb73-472d-8d96-7a222613deb3)

**Comment by Luedman** [comment]
Set `batch_size, seq_len = real.size(0), real.size(2)` then it should run.

**Comment by dawson-miller** [comment]
The variable **real** exists within the training loop, but the discriminator is defined prior to the first epoch, resulting in the error.

I added `batch_size, seq_len = log_returns_preprocessed.shape[0], log_returns_preprocessed.shape[1]` before the first epoch and the PyTorch notebook runs now.

**Comment by JamesSullivan** [comment]
Dawson-Miller, if you put in a pull request I will merge it.
